# Generated by Django 3.0.1 on 2020-02-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_entry_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='slug',
        ),
    ]
