# Generated by Django 3.0.2 on 2020-02-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_entry_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
