# Generated by Django 3.0.1 on 2020-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_entry_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parentID',
            field=models.IntegerField(default=0),
        ),
    ]
